version: '2'
services:
  web:
    build: .
    container_name: my-web
    ports:
     - "5000:5000"
    volumes:
      - .:/var/www/html
    ports:
      - 8070:80
    depends_on:
      - db
    links:
      - db:my-db
  db:
    build:
      context: ./my-db
    image: my-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: oshry
      MYSQL_PASSWORD: oshry81
      MYSQL_DATABASE: my_db
    ports:
      - 3379:3306
    volumes:
      - ./my-db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=oshry81
    links:
      - db:my-db
    ports:
      - "8071:80"
